# Generated by Django 4.0.4 on 2023-11-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='food',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='order_id',
            new_name='order',
        ),
    ]
