# Generated by Django 4.0.4 on 2023-12-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_food_orders_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='food_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
